# Generated by Django 2.1 on 2018-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_textmessage_talktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='talktime',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
